"""
AI Data Contracts for NeoBright LMS - Phase 1.

Defines input/output types for AI features:
- INPUT: StudentContext (from Phase 0 AI Context Service)
- OUTPUT: AiInsights (generated by LLM)

All models use dataclasses for consistency with existing codebase.
"""
from dataclasses import dataclass, field, asdict
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


# ============================================================================
# INPUT CONTRACTS: What goes INTO the AI
# ============================================================================

class RiskLevel(Enum):
    """Risk levels for student performance."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


@dataclass
class CourseAnalytics:
    """Analytics for a single course."""
    id: str  # Course ID (e.g., "CSSB4113")
    name: str  # Course name (e.g., "Software Quality Assurance")
    progress: float  # Progress percentage (0-100)
    average_score: Optional[float] = None  # Grade average (0-100)
    completed_activities: int = 0  # Number of completed activities
    total_activities: int = 0  # Total activities in course
    last_access: Optional[str] = None  # ISO 8601 datetime string
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for JSON serialization."""
        return asdict(self)


@dataclass
class OverallAnalytics:
    """Overall analytics across all courses."""
    overall_progress: float  # Average progress across all courses (0-100)
    weekly_progress: List[float] = field(default_factory=list)  # Last 5 weeks of progress
    completion_rate: float = 0.0  # Fraction of activities completed (0-1)
    velocity_activities_per_week: float = 0.0  # Activities completed per week
    risk_level: str = "medium"  # "low", "medium", "high"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for JSON serialization."""
        return asdict(self)


@dataclass
class StudentContext:
    """
    Complete AI context for a student.
    
    This is the INPUT to all AI features (insights, recommendations, etc).
    Built by AIContextService from Phase 0.
    """
    student_id: str  # Firebase UID
    name: str  # Student display name
    courses: List[CourseAnalytics] = field(default_factory=list)
    analytics: Optional[OverallAnalytics] = None
    timestamp: Optional[str] = None  # ISO 8601 datetime when context was built
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for JSON serialization."""
        data = asdict(self)
        if self.analytics:
            data['analytics'] = self.analytics.to_dict()
        data['courses'] = [c.to_dict() for c in self.courses]
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'StudentContext':
        """
        Build StudentContext from dict (e.g., from API response).
        Used when consuming Phase 0 AI context endpoint.
        Handles both camelCase (from API) and snake_case (from internal).
        """
        # Helper to convert camelCase to snake_case
        def camel_to_snake(name: str) -> str:
            import re
            s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
            return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

        # Convert analytics
        analytics_data = data.get('analytics')
        analytics = None
        if analytics_data:
            # Convert camelCase keys to snake_case
            analytics_snake = {camel_to_snake(k): v for k, v in analytics_data.items()}
            analytics = OverallAnalytics(**analytics_snake)

        # Convert courses
        courses_data = data.get('courses', [])
        courses = []
        for course in courses_data:
            # Convert camelCase keys to snake_case
            course_snake = {camel_to_snake(k): v for k, v in course.items()}
            courses.append(CourseAnalytics(**course_snake))

        return cls(
            student_id=data['student']['id'],
            name=data['student']['name'],
            courses=courses,
            analytics=analytics,
            timestamp=data.get('timestamp')
        )


# ============================================================================
# OUTPUT CONTRACTS: What comes OUT of the AI
# ============================================================================

@dataclass
class AiActionItem:
    """A single actionable item for student."""
    title: str  # Short title (e.g., "Complete Quiz 3")
    description: str  # Detailed description of action
    deadline_days: Optional[int] = None  # Days to complete (e.g., 7 for this week)
    course_id: Optional[str] = None  # Which course this relates to
    priority: str = "medium"  # "low", "medium", "high"
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for JSON serialization."""
        return asdict(self)


@dataclass
class AiInsights:
    """
    Complete AI insights for a student.
    
    This is the OUTPUT of all AI features.
    Generated by LLM based on StudentContext input.
    """
    # Core insights
    summary: str  # 1-2 sentence overall summary of student status
    strengths: List[str] = field(default_factory=list)  # 2-3 things student does well
    areas_to_improve: List[str] = field(default_factory=list)  # 2-3 focus areas
    
    # Actionable recommendations
    actions: List[AiActionItem] = field(default_factory=list)  # 3-5 specific actions
    
    # Metadata
    risk_level: str = "medium"  # "low", "medium", "high" (mirrored from context)
    confidence_score: Optional[float] = None  # 0-1 confidence in analysis
    generated_at: Optional[str] = None  # ISO 8601 when insights were generated
    context_timestamp: Optional[str] = None  # Timestamp of input context
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for JSON serialization."""
        data = asdict(self)
        data['actions'] = [a.to_dict() for a in self.actions]
        return data


# ============================================================================
# API RESPONSE MODELS
# ============================================================================

@dataclass
class AiInsightsResponse:
    """Response wrapper for /api/ai/insights endpoint."""
    success: bool
    data: Optional[AiInsights] = None
    error: Optional[str] = None
    error_details: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dict for JSON serialization."""
        data_dict = self.data.to_dict() if self.data else None
        return {
            'success': self.success,
            'data': data_dict,
            'error': self.error,
            'error_details': self.error_details
        }
